[package]
name = "musig-dll"
authors = ['The ChainX Authors']
edition = "2018"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
schnorrkel = "0.10.1"
hex = "0.4.3"
hex-literal = "0.3.1"
libc = "0.2"