on: [push, pull_request]

name: threshold-signature

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install linux deps
        run: |
          sudo apt update
          sudo apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio
      
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          target-subdir-name: musig-dll
        
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-30
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
          components: rustfmt, rust-src, clippy

      - name: Run cargo check
        run: |
          cd musig-dll
          cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install linux deps
        run: |
          sudo apt update
          sudo apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio
      
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-30
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
          components: rustfmt, rust-src, clippy

      - name: Run cargo test
        run: |
          cd musig-dll
          cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Install linux deps
        run: |
          sudo apt update
          sudo apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio
      
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-30
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
          components: rustfmt, rust-src, clippy

      - name: Run cargo fmt
        run: |
          cd musig-dll
          cargo fmt --all -- --check

      - name: Run cargo clippy
        run: |
          cd musig-dll
          cargo clippy --all --all-targets -- -D warnings
